# wavelet.conf example
# Parsed by install_wavelet_server.sh

# The password for the two wavelet users.
PASSWORD=testlab123
DOMAIN=wavelet.allethrium
# Network gateway
SVR_GW=192.168.1.1
# Server static IP (must be static)
SVR_IP=192.168.1.32
# Registry for the deployment server
DEPLOYMENT_REGISTRY=deploy.wavelet.allethrium
# Deployment IP
DEPLOYMENT_IP=192.168.1.252
# Server registry (usually the same IP as the server, and if undefined defaults to that value)
REGISTRY=192.168.1.32
# Pulls from the working branch for newer features
DEVELOPER_MODE=1
# WiFi will be favored for connectivity
ENABLE_WIFI=1
WIFI_SSID=Wavelet-LAB
# Does not need to be the entire Access Point MAC address
WIFI_BSSID=00:01:02
# IP Address of the AP (automatically added to network infra)
WIFI_IP_ADDR=192.168.1.?
# IP Address of other Infra in type:IP format which may benefit from monitoring
NETWORK_INFRA1=switch:192.168.1.2
#NETWORK_INFRA2=ups:192.168.1.3
# Targets the patched version of UltraGrid instead of upstream
# Wavelet expects certain control port API features and will break without them, so this should not be modified.
UG_BUILD_TYPE=DEV
# Wifi AP credentials
WIFI_DEVICE_PASSWORD=superGoodPassword
WIFI_DEVICE_USER=administrator
# This is always set to this value, as we need a specific patched UltraGrid binary
UG_BUILD_TYPE=DEV

