<?php
header('Location: http://192.168.1.32:8180/index.html');
$input = $_POST['inVar'];
$memory = memory_get_usage();
$strlength = strlen($input);


// Sanitize inputs - hard to do anything nefarious with three chars
if ($strlength >= 3) {
        echo nl2br("Input exceeds maximum post value, ending process.");
} else {
    if ($_GET['do'] === "refresh") {
        get_ecd_inputs();
    } else {
        // Perform additional validation and sanitation here before calling set_etcd()
        $input = trim($_POST['input']); // Trim leading and trailing whitespace
        if (preg_match('/^[a-zA-Z0-9\s_]+$/', $input))
        set_etcd($input)
        }


// Sets selected variable into etcd
function set_etcd (str $string) {
    echo nl2br("\n Input is {$input}\n ");
    $base64_value = base64_encode($input);
    echo nl2br("\n Encoded Base64 input value is {$base64_value} \n");

    // create a new cURL resource
    // example of a valid cURL command:
    // curl -L http://192.168.1.32:2379/v3/kv/put -X POST -d '{"key":"aW5wdXQ=", "value":"Mw=="}'
    echo nl2br("\n Attempting to Curl {$base64_value} into etcd..\n ");
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'http://192.168.1.32:2379/v3/kv/put');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"key\":\"aW5wdXQ=\", \"value\":\"$base64_value\"}");

    $headers = array();
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

// gets a keypair value from etcd - use for error messages in future, idk
function get_etcd(str $string) {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'http://192.168.1.32:2379/v3/kv/get'); // Replace this with your actual etcd server URL and port number
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_GET, true);
    curl_setopt($ch, CURLOPT_QUOTE, true);
    curl_setopt($ch, CURLOPT_CURLAUTH, CURLAUTH_ANY);
    curl_setopt($ch, CURLOPT_HEADERFUNCTION, 'myHeaderCallback'); // Replace this with your own custom header function or remove it if you don't need one
    // curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"key\":\"$my_key\", \"value\":\"$my_value\"}"); // Replace $my_key and $my_value with your actual key
}

// gets the list of available inputs from etcd and hopefully we can AJAX this into the webUI inputs div with minimal fuss..
function get_etcd_inputs() {
    // For testing purposes, i commented all of this out and it's just a static array of things that would look like what etcd would spit out
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    // $ch = curl_init();
    // curl_setopt($ch, CURLOPT_URL, 'http://192.168.1.32:2379/v3/kv/range');
    // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    // curl_setopt($ch, CURLOPT_POST, 1);
    // curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"key\": \"AA==\", \"range_end\": \"AA==\"}");
// 
    // $headers = array();
    // $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    // curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
// 
    //$resultArray = curl_exec($ch);
    //if (curl_errno($ch)) {
    //    echo 'Error:' . curl_error($ch);
    //curl_close($ch);
 //   var implodedArray = 
 // probably don't need this since output is unserialized?       echo '["' . implode('", "', $output) . '"]'
    $resultArray = array("IPEVO Ziggi Document Camera", "Magewell HDMI Capture", "Magewell HDMI Capture+", "Logitech HDMI Capture (USBaddr)", "Some unknown input source that magically works");
}

function return_inputs_list() {
    $output = (get_etcd_inputs);
    print_r($output);
}
?>