<?php
header('Location: http://192.168.1.32:8180/index.html');
$input = $_POST['inVar'];
$memory = memory_get_usage();
$strlength = strlen($input);


// Sanitize inputs - hard to do anything nefarious with three chars
if ($strlength >= 3) {
        echo nl2br("Input exceeds maximum post value, ending process.");
} else
    echo nl2br("\n Input is {$input}\n ");
    $base64_value = base64_encode($input);
    echo nl2br("\n Encoded Base64 input value is {$base64_value} \n");

    // create a new cURL resource
    // example of a valid cURL command:
    // curl -L http://192.168.1.32:2379/v3/kv/put -X POST -d '{"key":"aW5wdXQ=", "value":"Mw=="}'
    echo nl2br("\n Attempting to Curl {$base64_value} into etcd..\n ");
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'http://192.168.1.32:2379/v3/kv/put');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"key\":\"aW5wdXQ=\", \"value\":\"$base64_value\"}");

    $headers = array();
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
?>

// this would be needed to process outputs from ECTCD
// input translates to "aW5wdXQ=" in Base64 encoding, which is used by etcd'3 V3 gRPC API.
// $jsondata = (curl -sL http://192.168.1.32:2379/v3/kv/range -X POST -d '{"key":"aW5wdXQ="}')

// https://stackoverflow.com/questions/29308898/how-to-extract-and-access-data-from-json-with-php - decode the JSON
// we need ONLY the value field out of this
// $data = json_decode($jsonData, true);
// $value = $data["value"];

// need this to decode the return string
// $decode_value = base64_decode($value);