<?php
header('Content-type: application/json');
include('get_auth_token.php');

// POST fields from JS AJAX will only ever single entries.  We extract them both here.
$hash = $_POST["value"];
$label = $_POST["label"];

// create a new cURL resource
    // example of a valid cURL command:
    // curl -L http://192.168.1.32:2379/v3/kv/put -X POST -d '{"key":"aW5wdXQ=", "value":"Mw=="}'
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

function curl_etcd($keyTarget, $keyValue, $token) {
	$b64KeyTarget = base64_encode($keyTarget);
	$b64KeyValue = base64_encode($keyValue);
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, 'http://192.168.1.32:2379/v3/kv/put');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"key\":\"$b64KeyTarget\", \"value\":\"$b64KeyValue\"}");
	$headers = array();
<<<<<<< Updated upstream
	$headers = [
		"Authorization: $token",
		"Content-Type: application/json"
	];
=======
	$headers[] = 'Authorization: ' .  $token;
	$headers[] = 'Content-Type: application/x-www-form-urlencoded';
>>>>>>> Stashed changes
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	echo "Succesfully set {$keyTarget} for {$keyValue} \n";
}

// curl etcd uv_hash_select for the value of the device hash we want to see streaming on the system
<<<<<<< Updated upstream
$token=get_etcd_authtoken;
=======
$token	= get_etcd_auth_token();
>>>>>>> Stashed changes
curl_etcd("/UI/UV_HASH_SELECT", $hash);
curl_etcd("/UI/UV_INPUT", $label);
curl_etcd("/UI/INPUT_UPDATE", "1");
?>