#	This file primarily references the following sources;
#	https://github.com/coreos/layering-examples/blob/main/build-zfs-module/Containerfile
#	https://github.com/coreos/layering-examples/blob/main/replace-kernel/Containerfile
#	https://github.com/coreos/layering-examples
#	https://coreos.github.io/rpm-ostree/layering/
#	https://travier.github.io/rpm-ostree/cliwrap/

# This containerfile aims to build all dependencies for Wavelet in a container for client systems.  It's the "base layer"
# To be applied as an ostree rebase

FROM quay.io/fedora/fedora-coreos:43.20260301.3.1

# Step 1: Configure repos and install packages that don't conflict with Fedora defaults
RUN rpm-ostree override remove nfs-utils-coreos --install nfs-utils
RUN rm /etc/yum.repos.d/fedora-cisco-openh264.repo && \
    curl -o /etc/yum.repos.d/swayfx.repo https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/repo/fedora-43/swayfx-swayfx-fedora-43.repo && \
    rpm-ostree install -y -A \
        wget fontawesome-fonts wl-clipboard nnn mako swayfx swayimg bemenu rofi-wayland lxsession \
        xwayland-run waybar chrony foot vim powerline powerline-fonts vim-powerline greetd \
        NetworkManager-wifi iw wireless-regdb wpa_supplicant nfs-utils \
        avahi nss-mdns rdma freeipa-client \
        iwlwifi-dvm-firmware.noarch iwlwifi-mvm-firmware.noarch intel-audio-firmware intel-gpu-firmware intel-vsc-firmware \
        alsa-firmware alsa-sof-firmware realtek-firmware \
        etcd sha \
        libv4l v4l-utils pipewire-v4l2 pipewire-gstreamer pulseaudio-utils ImageMagick \
        mesa-dri-drivers mesa-vulkan-drivers libdrm mesa-libEGL mesa-libgbm mesa-libGL \
        alsa-lib pipewire-alsa alsa-plugins-speex bluez-tools nmap-ncat \
        tuned realtime-tests rtkit jo linuxptp linuxptp-selinux \
        intel-gpu-tools intel-compute-runtime intel-gmmlib intel-opencl \
        intel-level-zero libvpl \
        libva libva-utils libva-v4l2-request libvdpau \
        oneVPL-intel-gpu oneapi-level-zero opencl-headers mpv libsrtp \
        fastfetch btop mesa-libOpenCL srt srt-libs pipewire-utils usbutils \
        plymouth plymouth-system-theme plymouth-theme-fade-in plymouth-theme-spinfinity \
        plymouth-plugin-script plymouth-scripts \
        rkhunter clamav clamd clamav-freshclam firefox && \
    # Step 2: Install rpmfusion repos, then replace Fedora's free ffmpeg with rpmfusion version
    rpm-ostree install -y -A \
        https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
        https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    rpm-ostree override remove \
        libavcodec-free libavfilter-free libavformat-free libavutil-free \
        ffmpeg-free libpostproc-free libswresample-free libswscale-free libavdevice-free && \
    rpm-ostree install -y -A \
        ffmpeg ffmpeg-libs intel-media-driver libheif-freeworld \
        libndi-sdk ndi-sdk-documentation \
        libva-intel-driver vlc \
        gstreamer1-plugin-libav gstreamer1-plugins-bad-free-extras \
        gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly && \
    ostree container commit
