name: Generate Checksum

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate checksums
        uses: Solratic/checksum-action@v1
        with:
          pattern: "*.tar.xz"
          suffix: "checksum"
          subfolder: "checksums"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
